# Development config

version: '3.9'
services:
  nginx:
    depends_on:
      - panel
    volumes:
      - './config:/etc/letsencrypt/live/test.specifysystems.org-0001:ro'

  panel:
    build:
      context: ./.
      target: dev-runner
    # depends_on:
    #   - mariadb
    networks:
      - database
      - nginx
    restart: unless-stopped
    volumes:
      - './state:/home/node/state'
      - './app:/home/node/app'
