# Production config

services:
  nginx:
    depends_on:
      - panel
    volumes:
      - '/etc/letsencrypt/live:/etc/letsencrypt/live:ro'
      - '/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro'

  panel:
    build:
      context: ./.
      target: runner
    # depends_on:
    #   - mariadb
    networks:
      - database
      - nginx
    restart: unless-stopped
    volumes:
      - 'state:/home/node/state'
      - 'nginx-conf:/home/node/nginx.conf.d'
