# Development config

version: '3.9'
services:
  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    depends_on:
      - panel

  report-runner:
    extends:
      file: docker-compose.base.yml
      service: report-runner

  panel:
    build:
      context: ./.
      target: dev-runner
    depends_on:
      - mariadb
    networks:
      - database
      - nginx
    restart: unless-stopped
    volumes:
      - './:/app/'

volumes:
  database:

networks:
  database:
  nginx:
