version: '3.9'
services:
  mariadb:
    image: mariadb:10.6.4-focal
    networks:
      - database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - 'database:/var/lib/mysql'
      - './seed-database/:/docker-entrypoint-initdb.d/:ro'

  redis:
    image: redis
    networks:
      - redis

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx
    restart: unless-stopped
    volumes:
      - 'nginx-conf:/etc/nginx/conf.d/servers:ro'
      - './config/panel.conf:/etc/nginx/conf.d/default.conf:ro'

      - '/etc/letsencrypt/live:/etc/letsencrypt/live:ro'
      - '/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro'

  report-runner:
    image: specifyconsortium/report-runner
    networks:
      - database

volumes:
  database:
  state:
  nginx-conf:

networks:
  database:
  nginx:
  redis:
