# Production config
services:
  nginx:
    depends_on:
      - panel
    volumes:
      - '/etc/letsencrypt/live:/etc/letsencrypt/live:ro'
      - '/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro'

  panel:
    container_name: panel
    build:
      context: ./.
      target: runner
    depends_on:
      - mariadb
    networks:
      - database
      - nginx
    restart: unless-stopped
    user: "1000:988"
    volumes:
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - 'state:/home/node/state'
      - 'nginx-conf:/home/node/nginx.conf.d'
    environment:
      - DOCKER_LOG_PATH=/var/lib/docker/containers
