name: Typescript Typechecker

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Typecheck
        run: npm run test
